git clone git@github.com:huangming/BPupd.git
git clone git@github.com:huangming/baidu-maps-services-python.git
git clone git@github.com:huangming/fuckZD.git
git clone git@github.com:huangming/pyqt_config.git
git clone git@github.com:huangming/CNCRS.git
git clone git@github.com:huangming/blog_sources.git
git clone git@github.com:huangming/idcard.git
git clone git@github.com:huangming/python_dll_excel.git
git clone git@github.com:huangming/CNCRS_KBSS.git
git clone git@github.com:huangming/bpwork.git
git clone git@github.com:huangming/kcbplog.git
git clone git@github.com:huangming/python_log.git
git clone git@github.com:huangming/apschedulertask.git
git clone git@github.com:huangming/dailycheck.git
git clone git@github.com:huangming/log_zz.git
git clone git@github.com:huangming/autotestkcbp.git
git clone git@github.com:huangming/dbfsplit.git
git clone git@github.com:huangming/dbfcheck.git
git clone git@github.com:huangming/myvimplugin.git
git clone git@github.com:huangming/gentelella.git
git clone git@github.com:huangming/learning.git
git clone git@github.com:huangming/pythondemo.git
git clone git@github.com:huangming/dbfwork.git
git clone git@github.com:huangming/ant-design-platform.git
git clone git@github.com:huangming/dotfiles.git
